# Generated by Django 5.2.6 on 2025-10-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lead_appointment_availability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='availability',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='locked_by',
        ),
        migrations.AlterModelOptions(
            name='sheetconfig',
            options={'verbose_name': 'Sheet Configuration', 'verbose_name_plural': 'Sheet Configuration'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='sheetconfig',
            name='sheet_id',
            field=models.CharField(help_text='Google Sheet ID from URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='sheetconfig',
            name='tab_name',
            field=models.CharField(help_text='Worksheet/Tab name within the sheet', max_length=255),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
